apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: foreman
spec:
  rules:
    - host: foreman-prod.local
      http:
        paths:
          - backend:
              serviceName: rails
              servicePort: 3000
            path: /

